#ifndef EXPORT_H
#define EXPORT_H
#include <QxOrm.h>

// USER
#ifdef _BUILDING_USER
    #define USER_DLL_EXPORT  QX_DLL_EXPORT_HELPER
#else
    #define USER_DLL_EXPORT  QX_DLL_IMPORT_HELPER
#endif

#ifdef _BUILDING_USER
    #define QX_REGISTER_HPP_USER  QX_REGISTER_HPP_EXPORT_DLL
    #define QX_REGISTER_CPP_USER  QX_REGISTER_CPP_EXPORT_DLL
#else
    #define QX_REGISTER_HPP_USER  QX_REGISTER_HPP_IMPORT_DLL
    #define QX_REGISTER_CPP_USER  QX_REGISTER_CPP_IMPORT_DLL
#endif


// DEVICE
#ifdef _BUILDING_DEVICE
    #define DEVICE_DLL_EXPORT  QX_DLL_EXPORT_HELPER
#else
    #define DEVICE_DLL_EXPORT  QX_DLL_IMPORT_HELPER
#endif

#ifdef _BUILDING_DEVICE
    #define QX_REGISTER_HPP_DEVICE  QX_REGISTER_HPP_EXPORT_DLL
    #define QX_REGISTER_CPP_DEVICE  QX_REGISTER_CPP_EXPORT_DLL
#else
    #define QX_REGISTER_HPP_DEVICE  QX_REGISTER_HPP_IMPORT_DLL
    #define QX_REGISTER_CPP_DEVICE  QX_REGISTER_CPP_IMPORT_DLL
#endif


// PATIENT
#ifdef _BUILDING_PATIENT
    #define PATIENT_DLL_EXPORT  QX_DLL_EXPORT_HELPER
#else
    #define PATIENT_DLL_EXPORT  QX_DLL_IMPORT_HELPER
#endif

#ifdef _BUILDING_PATIENT
    #define QX_REGISTER_HPP_PATIENT  QX_REGISTER_HPP_EXPORT_DLL
    #define QX_REGISTER_CPP_PATIENT  QX_REGISTER_CPP_EXPORT_DLL
#else
    #define QX_REGISTER_HPP_PATIENT  QX_REGISTER_HPP_IMPORT_DLL
    #define QX_REGISTER_CPP_PATIENT  QX_REGISTER_CPP_IMPORT_DLL
#endif

// MESURE_RECORD
#ifdef _BUILDING_MESURE_RECORD
    #define MESURE_RECORD_DLL_EXPORT  QX_DLL_EXPORT_HELPER
#else
    #define MESURE_RECORD_DLL_EXPORT  QX_DLL_IMPORT_HELPER
#endif

#ifdef _BUILDING_MESURE_RECORD
    #define QX_REGISTER_HPP_MESURE_RECORD  QX_REGISTER_HPP_EXPORT_DLL
    #define QX_REGISTER_CPP_MESURE_RECORD  QX_REGISTER_CPP_EXPORT_DLL
#else
    #define QX_REGISTER_HPP_MESURE_RECORD  QX_REGISTER_HPP_IMPORT_DLL
    #define QX_REGISTER_CPP_MESURE_RECORD  QX_REGISTER_CPP_IMPORT_DLL
#endif

// MESURE_STEP
#ifdef _BUILDING_MESURE_STEP
    #define MESURE_STEP_DLL_EXPORT  QX_DLL_EXPORT_HELPER
#else
    #define MESURE_STEP_DLL_EXPORT  QX_DLL_IMPORT_HELPER
#endif

#ifdef _BUILDING_MESURE_STEP
    #define QX_REGISTER_HPP_MESURE_STEP  QX_REGISTER_HPP_EXPORT_DLL
    #define QX_REGISTER_CPP_MESURE_STEP  QX_REGISTER_CPP_EXPORT_DLL
#else
    #define QX_REGISTER_HPP_MESURE_STEP  QX_REGISTER_HPP_IMPORT_DLL
    #define QX_REGISTER_CPP_MESURE_STEP  QX_REGISTER_CPP_IMPORT_DLL
#endif


// MEDICAL_TESTING_DATA
#ifdef _BUILDING_MEDICAL_TESTING_DATA
    #define MEDICAL_TESTING_DATA_DLL_EXPORT  QX_DLL_EXPORT_HELPER
#else
    #define MEDICAL_TESTING_DATA_DLL_EXPORT  QX_DLL_IMPORT_HELPER
#endif

#ifdef _BUILDING_MEDICAL_TESTING_DATA
    #define QX_REGISTER_HPP_MEDICAL_TESTING_DATA  QX_REGISTER_HPP_EXPORT_DLL
    #define QX_REGISTER_CPP_MEDICAL_TESTING_DATA  QX_REGISTER_CPP_EXPORT_DLL
#else
    #define QX_REGISTER_HPP_MEDICAL_TESTING_DATA  QX_REGISTER_HPP_IMPORT_DLL
    #define QX_REGISTER_CPP_MEDICAL_TESTING_DATA  QX_REGISTER_CPP_IMPORT_DLL
#endif


// HARDWARE
#ifdef _BUILDING_HARDWARE
    #define HARDWARE_DLL_EXPORT  QX_DLL_EXPORT_HELPER
#else
    #define HARDWARE_DLL_EXPORT  QX_DLL_IMPORT_HELPER
#endif

#ifdef _BUILDING_HARDWARE
    #define QX_REGISTER_HPP_HARDWARE  QX_REGISTER_HPP_EXPORT_DLL
    #define QX_REGISTER_CPP_HARDWARE  QX_REGISTER_CPP_EXPORT_DLL
#else
    #define QX_REGISTER_HPP_HARDWARE  QX_REGISTER_HPP_IMPORT_DLL
    #define QX_REGISTER_CPP_HARDWARE  QX_REGISTER_CPP_IMPORT_DLL
#endif
#endif // EXPORT_H
